- src/assets/css/example.css
- src/directives/dragula.directive.ts
- src/example-app.html
- src/examples.ts
- src/providers/dragula.provider.ts
closes https://github.com/valor-software/ng2-dragula/issues/4
> fix(dragulaModel): model sync works properly now

- README.md
@NathanWalker Hey, I have added several badges
please merge if you like it :)
> chore(readme): added badges

- package.json
- src/providers/dragula.provider.ts
closes https://github.com/valor-software/ng2-dragula/issues/28
> fix(removeModel): issue with callback

- .npmignore
- package.json
closes https://github.com/valor-software/ng2-dragula/issues/148
> chore(npm): ignore *.ts files on npm

- src/app/examples.ts
> fix the error in the demo

- package.json
Works with angular2 final. Updated rxjs, zone.js and angular deps.
> Update to angular2 final

- package.json
> Update dragula tp 3.7.2

- README.md
Changing the image links in README.md so they should display correctly also on the npmjs.com copy... #755
> Change local img refs to raw.githubusercontent.com

- README.md
Trivial change but more readable than the string in the attribute
> chore(readme): updates dragula input attribute

- .travis.yml
- MIGRATION-v2.md
- README.md
- lerna.json
- modules/demo/package.json
- modules/ng2-dragula/CHANGELOG.md
- modules/ng2-dragula/package.json
**Before submitting**
If your pull request includes changes to the library code:
**Description**
See the v2.0.0 milestone for the many issues/PRs dealt with. A changelog will appear in next soon.
> v2 release

- README.md
- modules/ng2-dragula/src/components/dragula.service.ts
- modules/ng2-dragula/src/spec/StaticService.ts
- modules/ng2-dragula/src/spec/dragula.service.spec.ts
**Relevant issues**
Ref #306 
**Before submitting**
If your pull request includes changes to the library code:
> Add indexes to dropModel and removeModel events

- modules/ng2-dragula/src/spec/StaticService.ts
While trying to create some unit tests for my application, I found this file that served me well as an example to mock the DragulaService. 
I noticed that some dependencies were unused or deprecated and decided to improve it. 😄
> Remove unused dependencies and replace deprecated rxjs method

- libs/ng2-dragula/project.json
fix(chore): updated version scripts
> fix(chore): updated version scripts

- .github/workflows/on-release.yml
fix(chore): fixed release files
> fix(chore): fixed release files

- .github/workflows/on-release.yml
Please briefly describe your changes, and explain any choices you made.
**Relevant issues**
Please include references to any relevant issues.
**Before submitting**
If your pull request includes changes to the library code:
> Fix ci git

- libs/ng2-dragula/package.json
fix(chore): added publish config to package.json file
> fix(chore): added publish config to package.json file

- libs/ng2-dragula/project.json
- scripts/set-version.ts
feat(chore): added set-version.ts file
> feat(chore): added set-version.ts file

- libs/ng2-dragula/tsconfig.lib.prod.json
fix(chore): fixed angularCompilerOptions
removed ivy compilation
> fix(chore): fixed angularCompilerOptions

- .github/workflows/on-release.yml
- CHANGELOG.md
- libs/ng2-dragula/package.json
- package-lock.json
- package.json
> Fix publish file

- CHANGELOG.md
- libs/ng2-dragula/package.json
- package.json
> Docs updates
